pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
output_dir: "/shared/s2/lab01/youngjoonjeong/seer/sibal"
data_dir: "/shared/s2/lab01/dataset/language-table/language_table_blocktoblock_4block_sim"
dataset: "language_table" #"bridgedata", "epickitchen"
resolution: 128
cond_frames: 6 #sthv2 = (1 or 2), bridgedata = 1, epickitchen = 1
num_frames: 16 #sthv2 = (12 or 16), bridgedata = 16, epickitchen = (12 or 16)

val_batch_size: 2

seed: 1004
revision: null
sample_iter: 8 #iteration times of inference
num_samples: 1 #number of sampling times for each video clip
scale: 7.5 #sample conditional scale
ddim_steps: 10 #number of ddim sampling steps
n_rows: 1 #rows in gif (rows <= total batch size)
mixed_precision: "fp16" #choices=["no", "fp16", "bf16"]
saved_global_step: 20000 # saved global steps of checkpoint folder

MAX_FVD_BATCH: 32
